import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/footer/footer";
import Navbar from "@/Components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "XIV store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className="mt-4">
        <Navbar/>
       </div>
        {children} 
       <div className="mt-10">
         <Footer/>
       </div>
        </body>
    </html>
  );
}
