import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/footer/footer";
import Navbar from "@/Components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navbar/>
        {/* {children} */}
        <Footer/>
        </body>
    </html>
  );
}
